LapZaWioslo/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LapZaWioslo.Data;
using LapZaWioslo.Models;

namespace LapZaWioslo.Controllers
{
    public class EventController : Controller
    {
        private readonly DBContext _context;

        public EventController(DBContext context)
        {
            _context = context;
        }

        // GET: Event
        public async Task<IActionResult> Index()
        {
            return View(await _context.EventInformation.ToListAsync());
        }

        // GET
        [Route("Event/Details/{name}")]
        public async Task<IActionResult> Details(string name)
        {
            if (name == null)
            {
                return NotFound();
            }

            var eventInformation = await _context.EventInformation
                .Include(eventData => eventData.Participants)
                .FirstOrDefaultAsync(m => m.Name == name);

            if (eventInformation == null)
            {
                return NotFound();
            }

            return View(eventInformation);
        }

        // GET: Event/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AdditionalQuestion,Description,StartDate,EndDate")] EventInformation eventInformation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventInformation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventInformation);
        }

        // GET: Event/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventInformation = await _context.EventInformation.FindAsync(id);
            if (eventInformation == null)
            {
                return NotFound();
            }
            return View(eventInformation);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AdditionalQuestion,StartDate,EndDate")] EventInformation eventInformation)
        {
            if (id != eventInformation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventInformation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventInformationExists(eventInformation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventInformation);
        }

        // GET: Event/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventInformation = await _context.EventInformation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventInformation == null)
            {
                return NotFound();
            }

            return View(eventInformation);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventInformation = await _context.EventInformation.FindAsync(id);
            _context.EventInformation.Remove(eventInformation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventInformationExists(int id)
        {
            return _context.EventInformation.Any(e => e.Id == id);
        }
    }
}

LapZaWioslo/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LapZaWioslo.Data;
using LapZaWioslo.Models;

namespace LapZaWioslo.Controllers
{
    public class ParticipantsController : Controller
    {
        private readonly DBContext _context;

        public ParticipantsController(DBContext context)
        {
            _context = context;
        }

        // GET: Participants
        public async Task<IActionResult> Index()
        {
            var dBContext = _context.Participant.Include(p => p.EventInformation);
            return View(await dBContext.ToListAsync());
        }

        // GET: Participants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant
                .Include(p => p.EventInformation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participants/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.EventInformation, "Id", "Id");
            return View();
        }

        // POST: Participants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventId,Name,Surname")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(participant);
                await _context.SaveChangesAsync();
                if (User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Details", "Event", new { id = participant.EventId });
                }
                return RedirectToAction("Index", "Home");
            }
            ViewData["EventId"] = new SelectList(_context.EventInformation, "Id", "Id", participant.EventId);
            return View(participant);
        }

        // GET: Participants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant.FindAsync(id);
            if (participant == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.EventInformation, "Id", "Id", participant.EventId);
            return View(participant);
        }

        // POST: Participants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventId,Name,Surname")] Participant participant)
        {
            if (id != participant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipantExists(participant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.EventInformation, "Id", "Id", participant.EventId);
            return View(participant);
        }

        // GET: Participants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant
                .Include(p => p.EventInformation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participant.FindAsync(id);
            _context.Participant.Remove(participant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParticipantExists(int id)
        {
            return _context.Participant.Any(e => e.Id == id);
        }
    }
}

LapZaWioslo/Views/Event/Create.cshtml
@model LapZaWioslo.Models.EventInformation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>EventInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalQuestion" class="control-label"></label>
                <input asp-for="AdditionalQuestion" class="form-control" />
                <span asp-validation-for="AdditionalQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LapZaWioslo/Views/Event/Delete.cshtml
@model LapZaWioslo.Models.EventInformation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventInformation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LapZaWioslo/Views/Event/Details.cshtml
@model LapZaWioslo.Models.EventInformation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div style="display: inline-block;">
        <h1>@Html.DisplayFor(model => model.Name)</h1>
    </div>
    <div style="display: inline-block; vertical-align: super; float: right; font-size: 2em;">
        <div style="display: inline-block;">
            <a asp-action="Index">
                <i class="fas fa-arrow-left"> </i>
            </a>
        </div>
        <div style="display: inline-block;">
            <a asp-action="Edit" asp-route-id="@Model.Id">
                <i class="fas fa-edit"></i>
            </a>
        </div>
    </div>
</div>

<hr />

<div>
    <div>
        <i class="far fa-clock"></i>
        @Html.DisplayFor(model => model.StartDate) / @Html.DisplayFor(model => model.EndDate)
    </div>
    <hr />
    <div>
        <i class="far fa-question-circle"></i>
        @Html.DisplayFor(model => model.AdditionalQuestion)
    </div>
    <hr />
    <div>
        <i class="fas fa-info"></i>
        @Html.DisplayFor(model => model.Description)
    </div>
</div>

<div style="margin-top:80px">
    @await Html.PartialAsync("EventParticipantsView", Model.Participants)
</div>

LapZaWioslo/Views/Event/Edit.cshtml
@model LapZaWioslo.Models.EventInformation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>EventInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalQuestion" class="control-label"></label>
                <input asp-for="AdditionalQuestion" class="form-control" />
                <span asp-validation-for="AdditionalQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LapZaWioslo/Views/Event/EventParticipantsView.cshtml
@model IEnumerable<LapZaWioslo.Models.Participant>

<p/>
<div style="margin-bottom:50px;">
    <div style="display:inline-block">
        <h3>Participants</h3>
    </div>
    <div style="display: inline-block; vertical-align: super; float:right">
        <a asp-action="Create" class="btn btn-success">
            <i class="fas fa-plus-square"></i> @SharedStringLocalizer["String.Button.CreateNew"]
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(@item.Name, "Details", "Participants", new { id = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.ActionLink(SharedStringLocalizer["String.Button.Edit"], "Edit", "Participants", new { id = item.Id }) |
                @Html.ActionLink(SharedStringLocalizer["String.Button.Details"], "Details", "Participants", new { id = item.Id }) |
                @Html.ActionLink(SharedStringLocalizer["String.Button.Delete"], "Delete", "Participants", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

LapZaWioslo/Views/Event/Index.cshtml
@model IEnumerable<LapZaWioslo.Models.EventInformation>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="margin-bottom:50px;">
    <div style="display:inline-block">
        <h1>Events</h1>
    </div>
    <div style="display: inline-block; vertical-align: super; float:right">
        <a asp-action="Create" class="btn btn-success" style="text-align:right">
            <i class="fas fa-plus-square"></i> @SharedStringLocalizer["String.Button.CreateNew"]
        </a>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th width="50%">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th width="15%" align="right">
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th width="15%" align="right">
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th width="20%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Name">@item.Name</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td align="right">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm" style="text-align:right">
                        <i class="fas fa-edit"></i> @SharedStringLocalizer["String.Button.Edit"]
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm" style="text-align:right">
                        <i class="far fa-trash-alt"></i> @SharedStringLocalizer["String.Button.Delete"]
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>